### ISSUE TITLE
Spinner not showing

### ISSUE THREAD

**Issue by Wipsly** [msurguy/ladda-bootstrap#54]
down vote
favorite
I want to use Ladda with Bootstrap and when click on my submit button the button is expanding to the left, but the spinner is not showing.

I am using Laravel.

I have included the css file in my head:

       {!! Html::style('css/plugins/ladda-themeless.min.css') !!} 
And I also included both js files at the end of the page.

       {!! Html::script('js/plugins/spin.js') !!}
       {!! Html::script('js/plugins/ladda.js') !!}
After that I bind the input submit

      <script>
        Ladda.bind( 'input[type=submit]' );
        </script>
This is my submit button:

      {!! Form::submit('Register', ['class' => 'btn btn-primary ladda-button', 'data-style' => 'expand-left']) !!}
As I said at the top. It seems to be working. When I click my submit button the button expands to the left side and I disabled, but the Spinner is missing.

Can you help me?

**Comment by drosa88** [comment]
I had the same issue, i´m using Laravel too. Please try to use a button instead of an input.

Change your code like this:

```
  {!! Form::button('Register', ['type' => 'submit', 'class' => 'btn btn-primary ladda-button', 'data-style' => 'expand-left']) !!}
```

Regards

**Comment by Wipsly** [comment]
Thank you very much! It works :+1:
