### ISSUE TITLE
publish on npm

### ISSUE THREAD

**Issue by evilebottnawi** [msurguy/ladda-bootstrap#56]

**Comment by ozanhazer** [comment]
+1

**Comment by ozanhazer** [comment]
bower doesn't hurt too...

**Comment by evilebottnawi** [comment]
I close due to inactivity, overload of issues

**Comment by Jokero** [comment]
@evilebottnawi WTF? Why not publish to npm? Oo

**Comment by evilebottnawi** [comment]
@Jokero sorry, i am not owner this repo and can't publish on npm
