### ISSUE TITLE
Content Security Policy Incompatability

### ISSUE THREAD

**Issue by 4ydx** [msurguy/ladda-bootstrap#58]
I believe that spin.js is creating a dom object with inline style attributes.  Is it possible to do this some other way?  I would like to avoid all inline style attributes on my site, but it appears that ladda wont allow me to do that.

**Comment by msurguy** [comment]
Ok, what is the reason to avoid inline styles?

**Comment by 4ydx** [comment]
The site where I am using ladda most likely wont allow for the following type of (possibly outdated?) example, but it is something I came across while reading about csp:

http://www.html5rocks.com/en/tutorials/security/content-security-policy/?redirect_from_locale=es
http://scarybeastsecurity.blogspot.com/2009/12/generic-cross-browser-cross-domain.html

If I am off base about what I am asking for, please let me know :)

**Comment by msurguy** [comment]
@4ydx sorry for late reply but I don't think this is a valid concern since inline styles are ok and are encouraged in web development to get the best performance.
