### ISSUE TITLE
Spinner is not a constructor

### ISSUE THREAD

**Issue by jkosir** [msurguy/ladda-bootstrap#6]
TypeError: Spinner is not a constructor

Using latest from dist, exact copy of ajax form example from http://msurguy.github.io/ladda-bootstrap/

**Comment by paulotruta** [comment]
It would be good to change the readme to say **_"You will need to include both the spin.min.js and ladda.min.js files"_** instead of _**"You will need to include both the spin.min.js and ladda.min.js files".**_.. Should cause less confusion ;)

**Comment by dearsina** [comment]
@paulotruta The order matters.
