### ISSUE TITLE
Demo page is broken on HTTPS

### ISSUE THREAD

**Issue by electricduck** [msurguy/ladda-bootstrap#61]
There's a reference to Bootstrap CSS over HTTP, which breaks when visiting the page at https://msurguy.github.io/ladda-bootstrap/ in Chrome/Blink-based browsers. Blink blocks mixed content completely.

**Comment by msurguy** [comment]
@electricduck updated! please check it out and close the issue if it's fixed :)

**Comment by electricduck** [comment]
Lookin' good!
